import 'package:hired_app/widgets/app_bar/custom_app_bar.dart';import 'package:hired_app/widgets/app_bar/appbar_leading_image.dart';import 'package:hired_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:hired_app/widgets/custom_pin_code_text_field.dart';import 'package:hired_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:hired_app/core/app_export.dart';class EnterOtpScreen extends StatelessWidget {const EnterOtpScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 31.v), child: Column(children: [Text("Enter OTP", style: theme.textTheme.headlineSmall), SizedBox(height: 10.v), Container(width: 282.h, margin: EdgeInsets.symmetric(horizontal: 22.h), child: RichText(text: TextSpan(children: [TextSpan(text: "We have just sent you 4 digit code via your email ", style: CustomTextStyles.titleSmallff87868c), TextSpan(text: "example@gmail.com", style: CustomTextStyles.titleSmallff0d0140)]), textAlign: TextAlign.center)), SizedBox(height: 37.v), Padding(padding: EdgeInsets.only(left: 16.h, right: 15.h), child: CustomPinCodeTextField(context: context, onChanged: (value) {})), SizedBox(height: 40.v), CustomElevatedButton(text: "Continue", onPressed: () {onTapContinue(context);}), SizedBox(height: 26.v), Padding(padding: EdgeInsets.symmetric(horizontal: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("Didn’t receive code?", style: CustomTextStyles.titleMediumGray500), Text("Resend Code", style: theme.textTheme.titleMedium)])), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgComponent1, margin: EdgeInsets.only(left: 24.h, top: 13.v, bottom: 13.v), onTap: () {onTapImage(context);}), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgComponent3, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 13.v))]); } 

/// Navigates back to the previous screen.
onTapImage(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the jobTypeScreen when the action is triggered.
onTapContinue(BuildContext context) { Navigator.pushNamed(context, AppRoutes.jobTypeScreen); } 
 }
